# -*- coding: utf-8 -*-
"""
/***************************************************************************
 loadStopPlacesBuss
                                 A QGIS plugin
 Henter stoppesteder i vestfold og telemark, bus.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-22
        copyright            : (C) 2021 by Vestfold og Telemark Fylkeskommune, ved Robin Ellingsen
        email                : robin.ellingsen@vtfk.no
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load loadStopPlacesBuss class from file loadStopPlacesBuss.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Hent_Stoppesteder import loadStopPlacesBuss
    return loadStopPlacesBuss(iface)
